In [52]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [53]:
result_path = Path("../results/downstream_task")
methods_list = ["uniform","psa", "kmm", "mrs-forest", "fw-mrs-temperature", "fw-mrs-temperature-svm"]
bias_types = ["less_positive_class"]
#bias_types = ["mean_difference"]
metrics = ["MMDs",]
less_bias_strengths = ["0.1"]
mean_bias_strengthts = ["0.8"]
data_set_replacer = {
    "diabetes": "Diabetes",
    "folktables_employment": "Employment",
    "folktables_income": "Income",
    "bank_marketing": "Bank Marketing",
    "hr_analytics": "HR Analytic",
    "german_credit": "German Credit",
    "breast_cancer": "Breast Cancer",
    "loan_prediction": "Loan",
    }

In [54]:
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in methods_list:
            if bias_type == "mean_difference":
                bias_strengths = mean_bias_strengthts
            else : 
                bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "similarity_results.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "MMD Mean": result_file["MMDs"]["mean"], 
                        "MMD Std": result_file["MMDs"]["sd"], 
                        
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [55]:
for bias_type in bias_types:
    if bias_type == "mean_difference":
        bias_strengths = mean_bias_strengthts
    else : 
        bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_mmd_values = []
            std_mmd_values = []
            for method in result_df["Method"].unique():

                mean_mmd = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MMD Mean"].iloc[0]
                mean_mmd_values.append(np.round(mean_mmd, 3))

                std_mmd = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MMD Std"].iloc[0]
                std_mmd_values.append(np.round(std_mmd, 3))

                

            print(f"{data_set_replacer[dataset]} \
& ${mean_mmd_values[0]}\\pm{std_mmd_values[0]}$ \
& ${mean_mmd_values[1]}\\pm{std_mmd_values[1]}$ \
& ${mean_mmd_values[2]}\\pm{std_mmd_values[2]}$ \
& ${mean_mmd_values[3]}\\pm{std_mmd_values[3]}$ \
& ${mean_mmd_values[4]}\\pm{std_mmd_values[4]}$ \
& ${mean_mmd_values[5]}\\pm{std_mmd_values[5]}$ \
\\\\")
    print("\n")

less_positive_class, 0.1
Diabetes & $0.034\pm0.005$ & $0.01\pm0.001$ & $0.004\pm0.0$ & $0.029\pm0.004$ & $0.028\pm0.004$ & $0.025\pm0.004$ \\
Employment & $0.066\pm0.005$ & $0.013\pm0.001$ & $0.007\pm0.001$ & $0.044\pm0.014$ & $0.029\pm0.01$ & $0.027\pm0.005$ \\
Income & $0.063\pm0.003$ & $0.016\pm0.002$ & $0.008\pm0.001$ & $0.047\pm0.01$ & $0.043\pm0.009$ & $0.028\pm0.001$ \\
Bank Marketing & $0.025\pm0.003$ & $0.01\pm0.001$ & $0.006\pm0.0$ & $0.023\pm0.002$ & $0.023\pm0.002$ & $0.022\pm0.001$ \\
HR Analytic & $0.026\pm0.003$ & $0.008\pm0.0$ & $0.003\pm0.0$ & $0.023\pm0.002$ & $0.019\pm0.002$ & $0.019\pm0.002$ \\
German Credit & $0.056\pm0.006$ & $0.032\pm0.003$ & $0.023\pm0.002$ & $0.052\pm0.004$ & $0.046\pm0.008$ & $0.048\pm0.008$ \\
Breast Cancer & $0.395\pm0.017$ & $0.139\pm0.021$ & $0.01\pm0.002$ & $0.278\pm0.026$ & $0.219\pm0.048$ & $0.262\pm0.103$ \\
Loan & $0.132\pm0.014$ & $0.08\pm0.014$ & $0.035\pm0.005$ & $0.114\pm0.014$ & $0.097\pm0.031$ & $0.09\pm0.022$ \\

In [56]:
result_df = result_df.replace({"uniform": "Uniform", "kmm": "KMM", "psa": "PSA", "mrs-forest": "MRS",
                               "fw-mrs-temperature-svm": "FW-MRS-SVM", "fw-mrs-temperature": "FW-MRS-RF"})
result_df

,Method,Data Set,MMD Mean,MMD Std,Bias Type,Bias Strength
0,Uniform,diabetes,0.033552,0.004772,less_positive_class,0.1
1,PSA,diabetes,0.010386,0.000577,less_positive_class,0.1
2,KMM,diabetes,0.003610,0.000241,less_positive_class,0.1
3,MRS,diabetes,0.029447,0.004105,less_positive_class,0.1
4,FW-MRS-RF,diabetes,0.027990,0.004156,less_positive_class,0.1
5,FW-MRS-SVM,diabetes,0.025218,0.003725,less_positive_class,0.1
6,Uniform,folktables_employment,0.066432,0.004896,less_positive_class,0.1
7,PSA,folktables_employment,0.013232,0.001144,less_positive_class,0.1
8,KMM,folktables_employment,0.007018,0.000521,less_positive_class,0.1
9,MRS,folktables_employment,0.043695,0.014120,less_positive_class,0.1
10,FW-MRS-RF,folktables_employment,0.028993,0.010256,less_positive_class,0.1
11,FW-MRS-SVM,folktables_employment,0.026636,0.004838,less_positive_class,0.1
12,Uniform,folktables_income,0.062788,0.003322,less_positive_class,0.1
13,PSA,folktables_income,0.015871,0.001843,less_positive_class,0.1
14,KMM,folktables_income,0.007678,0.000723,less_positive_class,0.1
15,MRS,folktables_income,0.047212,0.010241,less_positive_class,0.1
16,FW-MRS-RF,folktables_income,0.043102,0.009455,less_positive_class,0.1
17,FW-MRS-SVM,folktables_income,0.027934,0.001273,less_positive_class,0.1
18,Uniform,bank_marketing,0.024678,0.002561,less_positive_class,0.1
19,PSA,bank_marketing,0.009659,0.000670,less_positive_class,0.1
20,KMM,bank_marketing,0.005803,0.000410,less_positive_class,0.1
21,MRS,bank_marketing,0.022640,0.002097,less_positive_class,0.1
22,FW-MRS-RF,bank_marketing,0.022929,0.001572,less_positive_class,0.1
23,FW-MRS-SVM,bank_marketing,0.022023,0.001280,less_positive_class,0.1
24,Uniform,hr_analytics,0.025511,0.002826,less_positive_class,0.1
25,PSA,hr_analytics,0.008017,0.000440,less_positive_class,0.1
26,KMM,hr_analytics,0.002958,0.000235,less_positive_class,0.1
27,MRS,hr_analytics,0.022642,0.002448,less_positive_class,0.1
28,FW-MRS-RF,hr_analytics,0.019048,0.002205,less_positive_class,0.1
29,FW-MRS-SVM,hr_analytics,0.019027,0.001876,less_positive_class,0.1
30,Uniform,german_credit,0.055804,0.005666,less_positive_class,0.1
31,PSA,german_credit,0.032350,0.002866,less_positive_class,0.1
32,KMM,german_credit,0.022685,0.001857,less_positive_class,0.1
33,MRS,german_credit,0.051529,0.004259,less_positive_class,0.1
34,FW-MRS-RF,german_credit,0.046128,0.007799,less_positive_class,0.1
35,FW-MRS-SVM,german_credit,0.047534,0.007536,less_positive_class,0.1
36,Uniform,breast_cancer,0.394518,0.016738,less_positive_class,0.1
37,PSA,breast_cancer,0.138870,0.021228,less_positive_class,0.1
38,KMM,breast_cancer,0.009998,0.001769,less_positive_class,0.1
39,MRS,breast_cancer,0.277844,0.026328,less_positive_class,0.1
40,FW-MRS-RF,breast_cancer,0.219064,0.048463,less_positive_class,0.1
41,FW-MRS-SVM,breast_cancer,0.261775,0.102847,less_positive_class,0.1
42,Uniform,loan_prediction,0.132190,0.014352,less_positive_class,0.1
43,PSA,loan_prediction,0.080388,0.013868,less_positive_class,0.1
44,KMM,loan_prediction,0.034581,0.005261,less_positive_class,0.1
45,MRS,loan_prediction,0.114143,0.013508,less_positive_class,0.1
46,FW-MRS-RF,loan_prediction,0.096704,0.030596,less_positive_class,0.1
47,FW-MRS-SVM,loan_prediction,0.089549,0.021813,less_positive_class,0.1

In [57]:
result_df["Rank MMD"] = result_df.groupby("Data Set")["MMD Mean"].rank(ascending=True)
result_df[["Method", "Rank MMD"]].groupby("Method").mean()

            Rank MMD
Method
FW-MRS-RF      3.875
FW-MRS-SVM     3.250
KMM            1.000
MRS            4.875
PSA            2.000
Uniform        6.000