In [43]:
import pandas as pd
from pathlib import Path   
import numpy as np

In [ ]:
result_path = Path("../results/downstream_task")
bias_types = ["less_positive_class"]
less_bias_strengths = ["0.1"]
method_name_replacer = {"uniform": "Uniform", 
                        "kmm": "KMM",
                        "psa": "PSA",
                        "soft-mrs-linear": "Soft-MRS",
                        "mrs-forest": "MRS",
                        "fw-mrs-temperature": "FW-MRS",
                        "fw-mrs-temperature-svm": "FW-MRS$_{SVM}$",
                        }
data_set_replacer = {"diabetes": "Diabetes",
                    "folktables_employment": "Employment", 
                     "folktables_income": "Income",
                     "bank_marketing": "Bank Marketing",
                     "hr_analytics": "HR Analytic",
                     "german_credit": "German Credit", 
                     "breast_cancer": "Breast Cancer", 
                     "loan_prediction": "Loan",
                    }

data_set_targets = {"diabetes": "",
                    "folktables_employment": "", 
                     "folktables_income": "",
                     "bank_marketing": "",
                     "hr_analytics": "",
                     "german_credit": "", 
                     "breast_cancer": "", 
                     "loan_prediction": "",
                    }

In [45]:
dict_list = []
for dataset in data_set_replacer.keys():
    for bias_type in bias_types:
        for method in method_name_replacer.keys():
            bias_strengths = less_bias_strengths
            for bias_strength in bias_strengths:
                json_file = result_path / dataset / bias_type /  bias_strength/ method / "similarity_results_T.json"
                result_file = pd.read_json(str(json_file))
                dict_list.append(
                    {
                        "Method": method, "Data Set": dataset, 
                        "MMD Mean": result_file["MMDs"]["mean"], 
                        "MMD Std": result_file["MMDs"]["sd"], 
                        #"Relative Bias Mean": result_file["MMDs"]["mean"], 
                        #"Relative Bias Std": result_file["MMDs"]["sd"], 
                        "Bias Type": bias_type, "Bias Strength": bias_strength,
                    }
                                )
result_df = pd.DataFrame(data=dict_list)

In [ ]:
for bias_type in bias_types:
    bias_strengths = less_bias_strengths
    for bias_strength in bias_strengths:
        print(f"{bias_type}, {bias_strength}")
        for dataset in data_set_replacer.keys():
            mean_mmd_values = []
            std_mmd_values = []
            for method in result_df["Method"].unique():

                mean_mmd = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MMD Mean"].iloc[0]
                mean_mmd_values.append(np.round(mean_mmd, 4))

                std_mmd = result_df.loc[(result_df["Method"]==method) & (result_df["Bias Type"]==bias_type) & 
                                                    (result_df["Bias Strength"]==bias_strength) & 
                                                    (result_df["Data Set"]==dataset)]["MMD Std"].iloc[0]
                std_mmd_values.append(np.round(std_mmd, 3))

                

            print(f"{data_set_replacer[dataset]} \
& ${mean_mmd_values[0]}\\pm{std_mmd_values[0]}$ \
& ${mean_mmd_values[1]}\\pm{std_mmd_values[1]}$ \
& ${mean_mmd_values[2]}\\pm{std_mmd_values[2]}$ \
& ${mean_mmd_values[3]}\\pm{std_mmd_values[3]}$ \
& ${mean_mmd_values[4]}\\pm{std_mmd_values[4]}$ \
& ${mean_mmd_values[5]}\\pm{std_mmd_values[5]}$ \
& ${mean_mmd_values[6]}\\pm{std_mmd_values[6]}$ \
\\\\")
    print("\n")

less_positive_class, 0.1
Diabetes & $0.0358\pm0.006$ & $0.0217\pm0.003$ & $0.022\pm0.003$ & $0.0217\pm0.003$ & $0.0325\pm0.005$ & $0.0319\pm0.005$ \\
Employment & $0.0681\pm0.005$ & $0.0219\pm0.002$ & $0.024\pm0.002$ & $0.022\pm0.001$ & $0.0472\pm0.013$ & $0.0465\pm0.014$ \\
Income & $0.064\pm0.005$ & $0.0233\pm0.003$ & $0.0262\pm0.002$ & $0.023\pm0.002$ & $0.0501\pm0.011$ & $0.0514\pm0.011$ \\
Bank Marketing & $0.0282\pm0.003$ & $0.0226\pm0.002$ & $0.023\pm0.002$ & $0.0226\pm0.002$ & $0.027\pm0.002$ & $0.0269\pm0.003$ \\
HR Analytic & $0.0276\pm0.003$ & $0.0184\pm0.002$ & $0.0187\pm0.002$ & $0.0183\pm0.002$ & $0.0258\pm0.003$ & $0.0246\pm0.003$ \\
German Credit & $0.064\pm0.007$ & $0.0549\pm0.006$ & $0.0561\pm0.007$ & $0.0547\pm0.006$ & $0.0615\pm0.006$ & $0.0601\pm0.007$ \\
Breast Cancer & $0.3949\pm0.017$ & $0.0429\pm0.009$ & $0.1423\pm0.024$ & $0.0432\pm0.009$ & $0.2805\pm0.032$ & $0.2701\pm0.043$ \\
Loan & $0.1413\pm0.015$ & $0.0803\pm0.014$ & $0.1004\pm0.015$ & $0.0804\pm0.013$ & $0.1275\pm0.016$ & $0.1122\pm0.028$ \\

In [47]:
result_df = result_df.replace(method_name_replacer)
result_df

,Method,Data Set,MMD Mean,MMD Std,Bias Type,Bias Strength
0,Uniform,diabetes,0.035790,0.006027,less_positive_class,0.1
1,KMM,diabetes,0.021661,0.003101,less_positive_class,0.1
2,PSA,diabetes,0.021974,0.002963,less_positive_class,0.1
3,Soft-MRS,diabetes,0.021664,0.003074,less_positive_class,0.1
4,MRS,diabetes,0.032462,0.005429,less_positive_class,0.1
5,FW-MRS,diabetes,0.031861,0.005348,less_positive_class,0.1
6,FW-MRS$_{SVM}$,diabetes,0.030843,0.005947,less_positive_class,0.1
7,Uniform,folktables_employment,0.068065,0.005092,less_positive_class,0.1
8,KMM,folktables_employment,0.021865,0.001573,less_positive_class,0.1
9,PSA,folktables_employment,0.024042,0.001788,less_positive_class,0.1
10,Soft-MRS,folktables_employment,0.021971,0.001478,less_positive_class,0.1
11,MRS,folktables_employment,0.047241,0.012916,less_positive_class,0.1
12,FW-MRS,folktables_employment,0.046527,0.014330,less_positive_class,0.1
13,FW-MRS$_{SVM}$,folktables_employment,0.032905,0.005117,less_positive_class,0.1
14,Uniform,folktables_income,0.063995,0.005134,less_positive_class,0.1
15,KMM,folktables_income,0.023319,0.002842,less_positive_class,0.1
16,PSA,folktables_income,0.026209,0.002453,less_positive_class,0.1
17,Soft-MRS,folktables_income,0.023032,0.001991,less_positive_class,0.1
18,MRS,folktables_income,0.050118,0.010829,less_positive_class,0.1
19,FW-MRS,folktables_income,0.051369,0.010919,less_positive_class,0.1
20,FW-MRS$_{SVM}$,folktables_income,0.034201,0.002862,less_positive_class,0.1
21,Uniform,bank_marketing,0.028176,0.002776,less_positive_class,0.1
22,KMM,bank_marketing,0.022634,0.001817,less_positive_class,0.1
23,PSA,bank_marketing,0.022958,0.001663,less_positive_class,0.1
24,Soft-MRS,bank_marketing,0.022573,0.001744,less_positive_class,0.1
25,MRS,bank_marketing,0.026982,0.002461,less_positive_class,0.1
26,FW-MRS,bank_marketing,0.026948,0.002530,less_positive_class,0.1
27,FW-MRS$_{SVM}$,bank_marketing,0.027576,0.002590,less_positive_class,0.1
28,Uniform,hr_analytics,0.027595,0.003097,less_positive_class,0.1
29,KMM,hr_analytics,0.018422,0.002220,less_positive_class,0.1
30,PSA,hr_analytics,0.018713,0.002327,less_positive_class,0.1
31,Soft-MRS,hr_analytics,0.018276,0.002280,less_positive_class,0.1
32,MRS,hr_analytics,0.025805,0.002817,less_positive_class,0.1
33,FW-MRS,hr_analytics,0.024579,0.002736,less_positive_class,0.1
34,FW-MRS$_{SVM}$,hr_analytics,0.025066,0.003186,less_positive_class,0.1
35,Uniform,german_credit,0.064033,0.006621,less_positive_class,0.1
36,KMM,german_credit,0.054874,0.005913,less_positive_class,0.1
37,PSA,german_credit,0.056055,0.006544,less_positive_class,0.1
38,Soft-MRS,german_credit,0.054676,0.005709,less_positive_class,0.1
39,MRS,german_credit,0.061532,0.006233,less_positive_class,0.1
40,FW-MRS,german_credit,0.060059,0.007168,less_positive_class,0.1
41,FW-MRS$_{SVM}$,german_credit,0.063061,0.010146,less_positive_class,0.1
42,Uniform,breast_cancer,0.394904,0.017140,less_positive_class,0.1
43,KMM,breast_cancer,0.042864,0.009061,less_positive_class,0.1
44,PSA,breast_cancer,0.142252,0.023988,less_positive_class,0.1
45,Soft-MRS,breast_cancer,0.043192,0.008983,less_positive_class,0.1
46,MRS,breast_cancer,0.280492,0.032003,less_positive_class,0.1
47,FW-MRS,breast_cancer,0.270129,0.043125,less_positive_class,0.1
48,FW-MRS$_{SVM}$,breast_cancer,0.225623,0.073111,less_positive_class,0.1
49,Uniform,loan_prediction,0.141282,0.015288,less_positive_class,0.1
50,KMM,loan_prediction,0.080285,0.014295,less_positive_class,0.1
51,PSA,loan_prediction,0.100370,0.014911,less_positive_class,0.1
52,Soft-MRS,loan_prediction,0.080448,0.013103,less_positive_class,0.1
53,MRS,loan_prediction,0.127454,0.016340,less_positive_class,0.1
54,FW-MRS,loan_prediction,0.112250,0.027811,less_positive_class,0.1
55,FW-MRS$_{SVM}$,loan_prediction,0.110480,0.020158,less_positive_class,0.1

In [48]:
result_df["Rank MMD"] = result_df.groupby("Data Set")["MMD Mean"].rank(ascending=True)
result_df[["Method", "Rank MMD"]].groupby("Method").mean()

                Rank MMD
Method
FW-MRS             4.750
FW-MRS$_{SVM}$     4.625
KMM                1.500
MRS                5.625
PSA                3.000
Soft-MRS           1.500
Uniform            7.000